version: "3.5"
services:
  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./rules:/etc/prometheus/rules"
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
      - --web.enable-admin-api
  parosly:
    image: parosly/parosly:latest
    container_name: parosly
    ports:
      - "5000:5000"
    volumes:
      - "./prometheus.yml:/app/prometheus.yml:rw"
      - "./rules:/app/rules:rw"
    command:
      - --prom.addr=http://prometheus:9090
      - --config.file=/app/prometheus.yml
      - --rule.path=/app/rules
      - --web.enable-ui=true